/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 speaker.glb --transform 
Files: speaker.glb [11.81MB] > E:\nier\public\speaker-transformed.glb [1.24MB] (90%)
Author: Mehdi Shahsavan (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/horn--speaker-30-mb-00858e6bf0644240afebadd5b858ab09
Title: Horn_ Speaker_30_MB
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/speaker-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['02_02_0'].geometry} material={materials.material} scale={0.01} />
      <mesh geometry={nodes['01_01_0'].geometry} material={materials.material_1} position={[-0.005, 1.052, 0.03]} scale={0.01} />
      <mesh geometry={nodes.Horn_Speaker_Horn_Speaker_0.geometry} material={materials.Horn_Speaker} position={[0, 5.446, 0]} scale={0.01} />
      {props.children}
    </group>
  )
}

useGLTF.preload('/speaker-transformed.glb')
